version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-todo
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - todo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tododb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - PG_USER=admin
      - PG_PASSWORD=password
      - PG_DB=tododb
      - PG_HOST=db
      - PG_PORT=5432
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    healthcheck: 
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    environment: 
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on: 
      backend:
        condition: service_healthy
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
